### ISSUE TITLE
Question/Issue with the bridge supports!?!?!?!

### ISSUE THREAD

**Issue by Cordero808** [5axes/CustomSupportCylinder#15]
### Discussed in https://github.com/5axes/CustomSupportCylinder/discussions/14

<div type='discussions-op-text'>

<sup>Originally posted by **Cordero808** December 27, 2021</sup>
I am getting an issue when using the bridge support. I have tried to place the support but each time I slice it the support looks lts not going to print the supports where I put them. I haven't tried to print it as I don't want to waste the filament. Is this normal and when I print it will print the support bridge???

![Cura_Custome_Support_Issue](https://user-images.githubusercontent.com/77555823/147466376-28f95c4d-32cf-41cc-8ae7-965d584c2c4b.png)
![Cura_Custome_Support_Issue2](https://user-images.githubusercontent.com/77555823/147466377-7336eb1b-0765-48b0-acdb-5e3ec4ee5ab6.png)
![Cura_Custome_Support_Issue3](https://user-images.githubusercontent.com/77555823/147466699-8b0b5a0a-82ba-4863-afe9-999b96ea9eec.png)

</div>

**Comment by 5axes** [comment]
Without Feedback from  @Cordero808  I think I can close this issue.
