### ISSUE TITLE
Most support types are going through model interfering with the print/infill

### ISSUE THREAD

**Issue by jaydawgx7** [5axes/CustomSupportCylinder#19]
Firstly, thank you for this plugin as it actually makes supports usable in Cura! I finally just updated to Cura 5.1 from 4.13 and reinstalled/updated all of my plugins and noticed I'm having issues with all of the support shapes except `Cylinder.`   All of the other shapes protrude up into or through the model which adds extra material through the top of the part. As you can see in this screenshot, the `Tube` support goes into the part and the other supports go right through the top of the model (which actually shows will get printed). 

![NcZhIXvip0](https://user-images.githubusercontent.com/29764043/181350192-26794ce4-1e4f-4cd9-9ea5-a898fb511fbc.png)

**Comment by 5axes** [comment]
Different additional height regarding the support Style.
![image](https://user-images.githubusercontent.com/11015345/183243686-ae0e64f8-b7c6-45fd-9744-b375af13a93c.png)

- Cube : Size /2
- Cylinder + Tube : Size * 0.1
- Freeform : 0
- Abutment : Size
- Custom : support_interface_height parameter


Yes clearly  too much difference between the heights. Something to review but these values have been defined according to test cases so it will take me some time to decide which solution to keep.

**Comment by 5axes** [comment]
Not sure to change something... Regarding the "standard" use of the plugin the **additional height**  is addapted to their specific shape.
![image](https://user-images.githubusercontent.com/11015345/183244512-c2db0ba8-d648-4d0b-8bd9-9c01ad2e3312.png)

In case of Cylinder Shape , the height could be standardized with the cube case. But this support is mainly  used to support small area so in this case the additional  height  is much more limited.
![image](https://user-images.githubusercontent.com/11015345/183245169-5cf958f4-87ca-43e1-8209-32f3730178e1.png)

**Comment by 5axes** [comment]
V2.6.6 Modification to limite the support height to the model height.

**Comment by DuckersMcQuack** [comment]
Goes through the model for me as well. Just added it to cura 5.1.1

![NVIDIA_Share_BCeNOJ97c6](https://user-images.githubusercontent.com/9039370/195408804-cd08aa60-1505-4c27-8dbb-b218ecd8cb04.png)
