### ISSUE TITLE
Resizing the custom support moves the object it is attached to

### ISSUE THREAD

**Issue by konskarm** [5axes/CustomSupportCylinder#2]
**Cura version:**
Any

**OS:**
Windows 10 (likely any)

**Reproduction steps:**
1. Add a custom support (e.g. cylinder)
2. Resize the cylinder using uniform scaling

**Expected result:** 
The cylinder is resized based on its center (similar to the support blocker cube) and the model remains in its initial position.

**Actual results:** 
The cylinder is resized but it is also moving the model it is attached to.
![image](https://user-images.githubusercontent.com/19388042/96461283-78d0bb00-1224-11eb-8f68-ff4d7c860d94.png)

**Additional Info:**
This only happens when resizing the custom support. Moving or rotating the custom support does not affect the position or orientation of the model it is attached it.

**Comment by 5axes** [comment]
I don't see any problem in this behaviour .. This situation occurs when the option "Automatically drop models on the build plate" is activated . And it's normal. If you move or rotate the support under the build plate you should have the same result.
![option](https://user-images.githubusercontent.com/11015345/96468374-53e04600-122c-11eb-8ec1-3af2e568773f.JPG)

**Comment by 5axes** [comment]
Cannot be considered as an issue .. I'm closing it.
