### ISSUE TITLE
Object duplication

### ISSUE THREAD

**Issue by Adriex** [5axes/CustomSupportCylinder#22]
Hi! I was working with an object that needed 6 supports, so I placed 6 cilinders and then made 6 duplications of the object. This produced a BIG performance loss, at the point that I had to wait a solid minute when tried to rotate one of the duplicated objects.
Already checked that wasn´t the objects fault. Ended up duplicating the objects I needed and putting the supports one by one object.
In this second approach every time a cylindical support was placed, Cura freezed some seconds until the support appeared.
This didn´t happened in Cura 4.X.X. Wish I could propose more info about it
Thanks!

**Comment by 5axes** [comment]
Cannot really reproduce this issue, certainly a problem from cura itself. Slicing process is much more longer as you increase the number of element but no issue on the element manipulation.
![image](https://user-images.githubusercontent.com/11015345/188661222-585a99cc-4694-4859-bcb5-9d8b3f544767.png)

**Comment by 5axes** [comment]
Whithout new information, no need to keep it open
