### ISSUE TITLE
Custom support moves model up in Z axis 

### ISSUE THREAD

**Issue by jabbermacy** [5axes/CustomSupportCylinder#27]
Add support, scale, model moves on it's own  

https://i.imgur.com/LNFcdwn.png

**Comment by 5axes** [comment]
Same situation for every support / support blocker you add to your model. It's a Cura issue.

**Comment by jabbermacy** [comment]
> Same situation for every support you add to your model if the option "Automatically drop models to the build plate" is on. It's a Cura issue.

Actually not true support blockers don't cause this issue at all...

**Comment by 5axes** [comment]
Support blocker is not a custom support   if you use the Cura function to create a support you get the same issue. Nothing I can do on this problem.
