### ISSUE TITLE
Supports only generating one layer

### ISSUE THREAD

**Issue by Garywoo** [5axes/CustomSupportCylinder#3]
I've added a custom support, just simply by setting the size and clicking the underside of the model. When previewing the slicing, I can see there is only one layer being generated on the build plate. What's happening here?

Using Cura 4.7.1

![Cura_2020-10-23_06-53-07](https://user-images.githubusercontent.com/10392194/96962108-0dc20580-14fe-11eb-9c81-0b2593b86437.png)

![Cura_2020-10-23_06-53-13](https://user-images.githubusercontent.com/10392194/96962111-0ef33280-14fe-11eb-9380-7894c6479cd6.png)

**Comment by 5axes** [comment]
Hello,

You must share your project, With only this partial informations it's impossible to analyze your issue

**Comment by Garywoo** [comment]
Hmm, that doesn't seem to be possible. I've never saved a project in cura before, but when I save this one, cura crashes without saving anything.

**Comment by Garywoo** [comment]
I was able to save the project, but only before slicing. If I save after slicing, cura crashes. Slicing this file displays the issue.
[LS_Octopus_v5.5.zip](https://github.com/5axes/CustomSupportCylinder/files/5432333/LS_Octopus_v5.5.zip)

**Comment by 5axes** [comment]
As your support is quite small and the Infill density is very Low ( 5%) you should activate at least One "Support Wall Line Count" to get a result. It's not an issue form the Custom support cylinder plugin but it comes from your settings. I will close this issue.
![support_wall_line_count](https://user-images.githubusercontent.com/11015345/97157357-48cf6d80-1778-11eb-81c9-20867be9429f.JPG)
