### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by EklDuderino** [5axes/CustomSupportCylinder#31]
Is it possible to do something like custom tree supports, or paint on supports? I envy the paint on and tree supports of Prusa. Cura often does not auto generate tree supports where I need them, and the normal supports are lacking and encase my print. Cura produces better prints overall. Prusa gives me isses while printing constantly. Hoping for some type of custom tree or paint on supports for Cura in the future. Thank you!

**Comment by 5axes** [comment]
No it's not possible via a Plugin. This type of modifications must be done in Cura.

**Comment by EklDuderino** [comment]
Thank you for the prompt response. Cheers!
