### ISSUE TITLE
Adding a wider base for narrow support cylinders?

### ISSUE THREAD

**Issue by sityware** [5axes/CustomSupportCylinder#33]
If you look at my example, I require narrow cylinder supports.

![alt text](https://i.postimg.cc/13DB92Yr/image.png)

These can be fragile when printing, so would like the first two layers to be wide like micky mouse ears, circular tabs. To give a strong base.

![image](https://user-images.githubusercontent.com/31103915/226382521-5ed04a27-0706-457d-88c7-b3be23fc2a28.png)

Example

![image](https://user-images.githubusercontent.com/31103915/226383193-7cde7d25-9a44-4a54-b8c6-f1d86b356c35.png)

**Comment by 5axes** [comment]
You already have the possibility to define a narrow support. Just define an Angle and a Maximum Size for the base.

![image](https://user-images.githubusercontent.com/11015345/226394081-3cd199cf-108b-45c8-ada4-91ce4eae7283.png)

**Comment by sityware** [comment]
Apologies, completely missed this !
