### ISSUE TITLE
Saving causes the supports to move

### ISSUE THREAD

**Issue by TimyIsCool** [5axes/CustomSupportCylinder#37]
When I save and open the file, the supports have moved and ive tried this a few times now

**Comment by 5axes** [comment]
We need an UltiMaker Cura project file (**3MF**)  to be able to help you with this.
guide: https://support.ultimaker.com/s/article/1667411030205

**Comment by foormowniki** [comment]
I have had the same issue for a couple of months. I place custom supports, save the project, and close Cura. The next time I open the project, supports are moved in random directions. I've performed a clean Cura install with a cleared cash, and it keeps happening. 

Edit 2:
Link to 3mf files: https://we.tl/t-iMntyH6fmC

Edit:
- I can't reproduce it in Cura 5.4

**Comment by 5axes** [comment]
Certainly same issue as : https://github.com/5axes/CustomSupportCylinder/issues/38
