### ISSUE TITLE
Not slicing anymore on CURA 4.10

### ISSUE THREAD

**Issue by Lakemast** [5axes/CustomSupportCylinder#8]
Hi @5axes,

First of all, thanks for this great plugin.

Since I've updated my Cura to versio 4.10, I'm not able to slice when I put some
 custom supports. It says that is slicing but never get finished.

![Capturar](https://user-images.githubusercontent.com/25143692/128580804-02ca4e85-820a-4018-8821-5d6aa0cb11d3.PNG)

**Comment by 5axes** [comment]
Try to share a project with this issue, but looks like an upstream problem and not related to this plugin.

**Comment by Lakemast** [comment]
I was testing something and I noticed that when I put less than 30 pillar it can slice the file. But when I add more than 30 supports, it stucks on slicing. I tested other plugin and the same issue occurs. I really dont know what is happening. I also tested with different files and the same issue occurs when I add more than 30 supports

Here is the project as you asked. Thanks in advance!

[Face.3mf](https://drive.google.com/file/d/1e-kltjEpnpu6gsr8HzIYkhgNLkytQDSI/view?usp=sharing)

![Less than 30 supports](https://user-images.githubusercontent.com/25143692/128603264-3cec5a8f-27c1-40f2-9f0a-788c162e8b94.PNG)

**Comment by 5axes** [comment]
Nothing to do with the number of custom support, just an issue with your settings, try to reduce the value of the Initial Layer Line Width 200% seams to be to hight (Even 190% is ok , in general you should not reach the orange limit of a parameter it's never a good solution)
![image](https://user-images.githubusercontent.com/11015345/128680253-6b4bbfdb-49bd-488b-82cd-fbd96e40b6eb.png)

If you think it's a bug report this issue to the Cura issue tracker :  https://github.com/Ultimaker/Cura/issues
